<?php
// Access CSRF token generated by pages that include this header (if available)
$csrf_token = $_SESSION['csrf_token'] ?? '';
?>
<!-- Navbar Include -->
<nav class="navbar navbar-expand-lg navbar-dark navbar-rgb fixed-top shadow-lg">
    <div class="container">
      <a class="navbar-brand nav-title" href="index.php">Green Bites</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="nav">
        <ul class="navbar-nav ms-auto align-items-center">
          <li class="nav-item">
            <a class="nav-link <?php echo basename($_SERVER['PHP_SELF']) == 'index.php' ? 'active' : ''; ?>" href="index.php">Home</a>
          </li>
          
          <!-- Menu Dropdown -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle <?php echo in_array(basename($_SERVER['PHP_SELF']), ['drinks.php', 'breakfast.php', 'lunch.php', 'snacks.php']) ? 'active' : ''; ?>" href="#" id="menuDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Menu
            </a>
            <ul class="dropdown-menu dropdown-menu-custom" aria-labelledby="menuDropdown">
              <li><a class="dropdown-item <?php echo basename($_SERVER['PHP_SELF']) == 'drinks.php' ? 'active' : ''; ?>" href="drinks.php"><i class="bi bi-cup-straw me-2"></i>Drinks</a></li>
              <li><a class="dropdown-item <?php echo basename($_SERVER['PHP_SELF']) == 'breakfast.php' ? 'active' : ''; ?>" href="breakfast.php"><i class="bi bi-sunrise me-2"></i>Breakfast</a></li>
              <li><a class="dropdown-item <?php echo basename($_SERVER['PHP_SELF']) == 'lunch.php' ? 'active' : ''; ?>" href="lunch.php"><i class="bi bi-egg-fried me-2"></i>Lunch</a></li>
              <li><a class="dropdown-item <?php echo basename($_SERVER['PHP_SELF']) == 'snacks.php' ? 'active' : ''; ?>" href="snacks.php"><i class="bi bi-cookie me-2"></i>Snacks</a></li>
            </ul>
          </li>
          
          <li class="nav-item"><a class="nav-link" href="index.php#complaintsSection">Complaint</a></li>
          <li class="nav-item"><a class="nav-link" href="index.php#aboutusSection">About Us</a></li>

          <!-- Auth / Account area (updated dynamically via JS + check_session.php) -->
          <li class="nav-item ms-lg-3" id="authNavItem">
            <a class="btn btn-success px-4" href="login.php">Login</a>
          </li>
        </ul>
      </div>
    </div>
</nav>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    const authNavItem = document.getElementById('authNavItem');
    if (!authNavItem) return;

    // Small loading indicator while we check the session
    authNavItem.innerHTML = '<span class="text-white-50 small">Checking session...</span>';

    fetch('auth/check_session.php', {
      credentials: 'same-origin'
    })
      .then(response => response.json())
      .then(data => {
        if (!data || !data.logged_in) {
          authNavItem.innerHTML = '<a class="btn btn-success px-4" href="login.php">Login</a>';
          return;
        }

        const fullName = data.full_name || 'User';

        authNavItem.classList.add('dropdown');
        authNavItem.innerHTML = `
          <a class="nav-link dropdown-toggle text-white" href="#" id="userDropdown" role="button"
             data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-circle me-1"></i>
            <span class="d-none d-md-inline">Welcome, ${fullName}</span>
          </a>
          <ul class="dropdown-menu dropdown-menu-end shadow border-0 rounded-3 mt-2" aria-labelledby="userDropdown">
            <li><a class="dropdown-item" href="#"><i class="bi bi-person-lines-fill me-2"></i>View Profile</a></li>
            <li><a class="dropdown-item" href="#"><i class="bi bi-bag-check me-2"></i>My Orders</a></li>
            <li><hr class="dropdown-divider"></li>
            <li>
              <button class="dropdown-item text-danger" id="logoutButton">
                <i class="bi bi-box-arrow-right me-2"></i>Logout
              </button>
            </li>
          </ul>
        `;

        const logoutButton = document.getElementById('logoutButton');
        if (logoutButton) {
          logoutButton.addEventListener('click', function () {
            logoutButton.disabled = true;
            logoutButton.innerHTML = '<span class="spinner-border spinner-border-sm me-2"></span>Logging out...';

            const formData = new FormData();
            formData.append('csrf_token', <?php echo json_encode($csrf_token); ?>);

            fetch('auth/logout.php', {
              method: 'POST',
              credentials: 'same-origin',
              body: formData
            })
              .then(res => res.json())
              .then(json => {
                if (json && json.redirect) {
                  window.location.href = json.redirect;
                } else {
                  window.location.reload();
                }
              })
              .catch(() => {
                window.location.reload();
              });
          });
        }
      })
      .catch(() => {
        authNavItem.innerHTML = '<a class="btn btn-success px-4" href="login.php">Login</a>';
      });
  });
</script>
