<?php
// Access CSRF token generated by pages that include this header (if available)
$csrf_token = $_SESSION['csrf_token'] ?? '';

// Fetch categories from database for dynamic menu
global $conn;
$navCategories = [];
if (isset($conn)) {
    $catQuery = mysqli_query($conn, "SELECT id, name, icon FROM categories ORDER BY name ASC");
    while ($cat = mysqli_fetch_assoc($catQuery)) {
        $navCategories[] = $cat;
    }
}
?>
<!-- Navbar Include -->
<nav class="navbar navbar-expand-lg navbar-dark navbar-rgb fixed-top shadow-lg">
    <div class="container">
      <a class="navbar-brand nav-title d-flex align-items-center" href="index.php">
        <img src="images/logo-icon.svg" alt="Green Bites" class="navbar-logo me-2">
        <span class="brand-text">Green</span><span class="brand-text-white">Bites</span>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="nav">
        <ul class="navbar-nav ms-auto align-items-center">
          <li class="nav-item">
            <a class="nav-link <?php echo basename($_SERVER['PHP_SELF']) == 'index.php' ? 'active' : ''; ?>" href="index.php">Home</a>
          </li>
          
          <!-- Menu Dropdown - Dynamic from Database -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="menuDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Menu
            </a>
            <ul class="dropdown-menu dropdown-menu-custom" aria-labelledby="menuDropdown">
              <?php if (!empty($navCategories)): ?>
                <?php foreach ($navCategories as $navCat): 
                  $catSlug = strtolower(str_replace(' ', '-', $navCat['name']));
                  $catIcon = $navCat['icon'] ?: 'tag';
                  $catFile = 'category.php?id=' . $navCat['id'];
                ?>
                <li>
                  <a class="dropdown-item" href="<?php echo $catFile; ?>">
                    <i class="bi bi-<?php echo htmlspecialchars($catIcon); ?> me-2"></i><?php echo htmlspecialchars($navCat['name']); ?>
                  </a>
                </li>
                <?php endforeach; ?>
              <?php else: ?>
                <li><a class="dropdown-item text-muted" href="#">No categories available</a></li>
              <?php endif; ?>
            </ul>
          </li>
          
          <li class="nav-item"><a class="nav-link" href="index.php#complaintsSection">Complaint</a></li>
          <li class="nav-item"><a class="nav-link" href="index.php#aboutusSection">About Us</a></li>

          <!-- Auth / Account area (updated dynamically via JS + check_session.php) -->
          <li class="nav-item ms-lg-3" id="authNavItem">
            <a class="btn btn-success px-4" href="login.php">Login</a>
          </li>
        </ul>
      </div>
    </div>
</nav>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    const authNavItem = document.getElementById('authNavItem');
    if (!authNavItem) return;

    // Small loading indicator while we check the session
    authNavItem.innerHTML = '<span class="text-white-50 small">Checking session...</span>';

    fetch('auth/check_session.php', {
      credentials: 'same-origin'
    })
      .then(response => response.json())
      .then(data => {
        if (!data || !data.logged_in) {
          authNavItem.innerHTML = '<a class="btn btn-success px-4" href="login.php">Login</a>';
          return;
        }

        const fullName = data.full_name || 'User';

        authNavItem.classList.add('dropdown');
        authNavItem.innerHTML = `
          <a class="nav-link dropdown-toggle text-white user-dropdown-toggle" href="#" id="userDropdown" role="button">
            <i class="bi bi-person-circle me-1"></i>
            <span class="d-none d-md-inline">Welcome, ${fullName}</span>
          </a>
          <ul class="dropdown-menu dropdown-menu-end shadow border-0 rounded-3 mt-2" id="userDropdownMenu" aria-labelledby="userDropdown">
            <li><a class="dropdown-item" href="profile.php"><i class="bi bi-person-lines-fill me-2"></i>View Profile</a></li>
            <li><a class="dropdown-item" href="my_orders.php"><i class="bi bi-bag-check me-2"></i>My Orders</a></li>
            <li><a class="dropdown-item" href="#" id="cartMenuBtn"><i class="bi bi-cart3 me-2"></i>Cart <span class="badge bg-success ms-1" id="cartBadge">0</span></a></li>
            <li><hr class="dropdown-divider"></li>
            <li>
              <button class="dropdown-item text-danger" id="logoutButton">
                <i class="bi bi-box-arrow-right me-2"></i>Logout
              </button>
            </li>
          </ul>
        `;

        const logoutButton = document.getElementById('logoutButton');
        if (logoutButton) {
          logoutButton.addEventListener('click', function () {
            logoutButton.disabled = true;
            logoutButton.innerHTML = '<span class="spinner-border spinner-border-sm me-2"></span>Logging out...';

            const formData = new FormData();
            formData.append('csrf_token', <?php echo json_encode($csrf_token); ?>);

            fetch('auth/logout.php', {
              method: 'POST',
              credentials: 'same-origin',
              body: formData
            })
              .then(res => res.json())
              .then(json => {
                if (json && json.redirect) {
                  window.location.href = json.redirect;
                } else {
                  window.location.reload();
                }
              })
              .catch(() => {
                window.location.reload();
              });
          });
        }
        
        // Fix: Make user dropdown stable on click
        const userDropdownEl = document.getElementById('userDropdown');
        const userDropdownMenu = document.getElementById('userDropdownMenu');
        if (userDropdownEl && userDropdownMenu) {
          let userDropdownOpen = false;
          
          userDropdownEl.addEventListener('click', function(e) {
            e.preventDefault();
            e.stopPropagation();
            
            // Close other dropdowns first
            document.querySelectorAll('.nav-item.dropdown.show').forEach(function(d) {
              if (d !== authNavItem) {
                d.classList.remove('show');
                const menu = d.querySelector('.dropdown-menu');
                if (menu) menu.classList.remove('show');
              }
            });
            
            // Toggle user dropdown
            userDropdownOpen = !userDropdownOpen;
            if (userDropdownOpen) {
              authNavItem.classList.add('show');
              userDropdownMenu.classList.add('show');
            } else {
              authNavItem.classList.remove('show');
              userDropdownMenu.classList.remove('show');
            }
          });
          
          // Prevent dropdown from closing when clicking inside
          userDropdownMenu.addEventListener('click', function(e) {
            // Allow clicks on links to work normally
            if (e.target.tagName === 'A' || e.target.closest('a')) {
              return;
            }
            e.stopPropagation();
          });
          
          // Close when clicking outside
          document.addEventListener('click', function(e) {
            if (!authNavItem.contains(e.target)) {
              userDropdownOpen = false;
              authNavItem.classList.remove('show');
              userDropdownMenu.classList.remove('show');
            }
          });
        }
      })
      .catch(() => {
        authNavItem.innerHTML = '<a class="btn btn-success px-4" href="login.php">Login</a>';
      });
  });
  
  // Fix: Make all dropdowns stable on click
  document.querySelectorAll('.nav-item.dropdown > .nav-link.dropdown-toggle').forEach(function(dropdownToggle) {
    dropdownToggle.addEventListener('click', function(e) {
      e.preventDefault();
      const parent = this.closest('.dropdown');
      const isOpen = parent.classList.contains('show');
      
      // Close all other dropdowns
      document.querySelectorAll('.nav-item.dropdown.show').forEach(function(openDropdown) {
        if (openDropdown !== parent) {
          openDropdown.classList.remove('show');
          openDropdown.querySelector('.dropdown-menu').classList.remove('show');
        }
      });
      
      // Toggle current dropdown
      if (isOpen) {
        parent.classList.remove('show');
        parent.querySelector('.dropdown-menu').classList.remove('show');
      } else {
        parent.classList.add('show');
        parent.querySelector('.dropdown-menu').classList.add('show');
      }
    });
  });
  
  // Close dropdown when clicking outside
  document.addEventListener('click', function(e) {
    if (!e.target.closest('.nav-item.dropdown')) {
      document.querySelectorAll('.nav-item.dropdown.show').forEach(function(dropdown) {
        dropdown.classList.remove('show');
        dropdown.querySelector('.dropdown-menu').classList.remove('show');
      });
    }
  });
</script>
